### ISSUE TITLE
Russian symbols

### ISSUE THREAD

**Issue by vliubko** [SanUI/SanUI#1] opened 2018-08-18 19:00 UTC
Hi there!

Russian letters are not supported.
Can you fix it, please?
![screen shot 2018-08-18 at 21 59 53](https://user-images.githubusercontent.com/7632467/44302475-16bd5800-a332-11e8-8768-18f9374d6fa3.png)

**Comment by SanUI** [comment] 2018-08-19 06:01
Hi!
That's not easily fixable. The issue is that oUF_Hank uses a font that does not support russian chars.

If you'd be so inclined, please run

```lua
/script oUF_target.name:SetFont(SanUI[2].Medias.DamageFont, 32, "THICKOUTLINE")
```

ingame and see if that shows your name correctly (I don't meet many russian chars to test). If so, we'd need to find a font that looks good that  we could ship. But one thing after another...

If that fails, please replace `DamageFont` by any of `Font`, `UnitFrameFont`, `PixelFont` or `ActionBarFont`. Thanks for your help!

Btw you should hide Tukui's unitframes using its config, right now you're showing twice the whole info :)

**Comment by vliubko** [comment] 2018-08-19 07:57
```
/script oUF_target.name:SetFont(SanUI[2].Medias.DamageFont, 32, "THICKOUTLINE")
```
works fine, until game reload :)

**Comment by SanUI** [comment] 2018-08-19 08:33
Yeah it was just a test. To fix this for you now, you can put

```lua
oUF_target.name:SetFont(SanUI[2].Medias.DamageFont, 32, "THICKOUTLINE")
```
(untested, please just give it a shot, it will survive reloads however).

after line 19 of `SanUI\Misc.lua`. It's just a stopgap measure though, in the long run I'd like to find new fonts that support cyrillic. Testing fonts is just so tedious :(

**Comment by Mephirogob** [comment] 2019-07-30 05:30
SanUI , sorry for being necroposter but you have mentioned "you should hide Tukui's unitframes using its config" - can you please explain how to do it? I have recently started my own first druid and your ui is looking gorgeus, but these unit frames...

**Comment by SanUI** [comment] 2019-07-30 07:04
Open the file `Tukui/Config/Config.lua` in an editor, and then look for lines 126, 136 and 185. On those lines, change `true` to `false. That should do it :) Also have a look around that file for other settings that might interest you. If you loaded the addon `Tukui_Config` you could also use the ingame configuration, but I've never done so.

**Comment by Mephirogob** [comment] 2019-07-30 07:28
I have loaded tukui_config but no matter what i clicked unit frames was still there, so now i go for editing config.lua, thanks for your kind reply, sir! =)

**Comment by Mephirogob** [comment] 2019-08-05 03:48
Sorry to bother again, i have this issue on castbars - no spell name just ??? marks. Player names are ok. Is anything can be done with it?
![castbar](https://user-images.githubusercontent.com/53462367/62437710-8f4d3c80-b76e-11e9-99bf-cfd88c204d33.png)

upd. I have found a solution somewhat. \AddOns\Tukui\Medias\Fonts\uf_font.ttf must be replaced and voila.

upd2. https://www.1001fonts.com/coolvetica-font.html i have subbed fonts on these one, its free and are looking good, try them on )

**Comment by KillTheMule** [comment] 2019-08-10 18:43
Great, thanks for getting back to us after finding a solution :)

**Comment by SanUI** [comment] 2019-08-10 18:44
Great, thanks for getting back to us after finding a solution :)

**Comment by SanUI** [comment] 2020-11-12 19:17
I switched to using the fonts included in tukui, so this should be fixed.

**Closed as completed by SanUI** 2020-11-12 19:17 UTC
